# Plateformes de financement supportées par GitHub Sponsors
# Docs : https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: [chrysa]
# patreon: username
# ko_fi: username
# liberapay: username
# open_collective: username
