true: pull_request_review
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  label-when-approved:
    name: Label when approved
    runs-on: ubuntu-latest
    steps:
    - name: Label when approved by committers
      uses: TobKed/label-when-approved-action@0058d0094da27e116fad6e0da516ebe1107f26de
      with:
        comment: PR approved by at least one committer.
        label: Approved
        remove_label_when_approval_missing: 'false'
        require_committers_approval: 'true'
        token: ${{ github.token }}
name: Label when approved
permissions:
  contents: read
  pull-requests: write
