---
#############################################
### config for gitlabci-local
#############################################
.local:
    after: true
    all: false
    before: true
    display: true
    dump: true
    engine: docker,auto
    list: true
    manual: true
    network: host
    notify: true
    pipeline: false
    pull: true
    real_paths: true
    rmi: true
    sockets: true
    variables:
        DH_REGISTRY: docker.io
        DH_REGISTRY_PASSWORD: ''
        DH_REGISTRY_USER: ''
        DH_REPO: ''

image: docker/compose:latest

include:
    - local: ci-jobs.yaml
    - local: black/ci.yaml
    # - local: django-drf/ci.yaml
    - local: flake8/ci.yaml
    # - local:  flask/ci.yaml
    # - local: flask-db-migrations/ci.yaml
    - local: hadolint/ci.yaml
    - local: mypy/ci.yaml
    - local: pre-commit/ci.yaml
    - local: pytest/ci.yaml
    - local: pylint/ci.yaml
    - local: python-dev/ci.yaml
    - local: reorder-python-imports/ci.yaml
    - local: sphinx/ci.yaml

stages:
    - analyse
    - build
    - publish container version
    - publish container latest

variables:
    DOCKER_DRIVER: overlay
    COMPOSE_DOCKER_CLI_BUILD: 1
    HADOLINT_IMAGE: hadolint/hadolint:latest-debian

