---
default_language_version:
    python: python3.9
fail_fast: false
minimum_pre_commit_version: 3.0.4
repos:
    # - repo: meta
    #   hooks:
    #       - id: identity
    #         stages: [manual]
    #       - id: check-hooks-apply
    #         stages: [manual]
    #       - id: check-useless-excludes
    #        stages: [manual]
    - repo: https://github.com/asottile/setup-cfg-fmt
      rev: ccfe420a1f8a857343bed59c3b82897001926c5b
      hooks:
          - id: setup-cfg-fmt
    - repo: https://github.com/IamTheFij/docker-pre-commit.git
      rev: v2.1.1
      hooks:
          - id: docker-compose-check
            stages: [manual]
          - id: hadolint
            stages: [manual]
    - repo: https://github.com/cheshirekow/cmake-format-precommit
      rev: v0.6.13
      hooks:
          - id: cmake-format
            files: Makefile
          - id: cmake-lint
            files: Makefile
    - repo: https://github.com/frnmst/md-toc
      rev: 8.1.9
      hooks:
          - id: md-toc
            stages:
                - manual
    - repo: https://github.com/smian/pre-commit-makefile.git
      rev: 261f8fb4b31dfdc05d1a1d7fbde1f1462ecde66d
      hooks:
          - id: makefile-doc
            stages:
                - manual
    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: afd8f0c6aa189558286a1100a15f646ceb385944
      hooks:
          - id: markdownlint
            args: [--fix,]
    - repo: https://github.com/executablebooks/mdformat
      rev: 0cbd2054dedf98ec8366001c8a16eacfa85cebc1
      hooks:
          - id: mdformat
        # Optionally add plugins
            additional_dependencies:
                - mdformat-gfm
                - mdformat-black
    - repo: https://github.com/lovesegfault/beautysh.git
      rev: 9845efc3ea3e86cc0d41465d720a47f521b2799c
      hooks:
          - id: beautysh
            args: [--indent-size, '4']
    - repo: https://github.com/openstack/bashate.git
      rev: f5426a8c83b429b7bae80d9004bdebc73ebe8137
      hooks:
          - id: bashate
            args:
                - --ignore=E006,E020