---
fail_fast: false
minimum_pre_commit_version: 2.7.0
repos:
    # - repo: meta
    #   hooks:
    #       - id: identity
    #         stages: [manual]
    #       - id: check-hooks-apply
    #         stages: [manual]
    #       - id: check-useless-excludes
    #        stages: [manual]
    - repo: https://github.com/IamTheFij/docker-pre-commit.git
      rev: v2.1.0
      hooks:
          - id: docker-compose-check
            stages: [manual]
            files: docker-compose.[a-zZ-Z\-_]+.y[a]{0,1}ml$
          - id: hadolint
            args: [--config=.hadolint.yaml]
            files: (\.dockerfile|\.Dockerfile|Dockerfile)$
            stages: [manual]
    - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
      rev: v1.1.1
      hooks:
          - id: markdown-toc
            args: [--indent, '    ', -i]
            stages: [manual]
    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: 2a1a122656549317f4e92dc8ccc7e27e8b6d259b
      hooks:
          - id: markdownlint
            args: [--fix, --config=.markdownlint.yml]
    - repo: https://github.com/adrienverge/yamllint.git
      rev: 4f1bbc33dcb550b27a77e10c9831b9ff732bc5a8
      hooks:
          - id: yamllint
            args: [--config-file=.yamllint.yaml, --format, parsable, --strict]
            stages: [manual]
    - repo: https://github.com/smian/pre-commit-makefile.git
      rev: 261f8fb4b31dfdc05d1a1d7fbde1f1462ecde66d
      hooks:
          - id: makefile-doc
            stages: [manual]
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.1.0
      hooks:
          - id: yamlfmt
    - repo: https://github.com/pre-commit/mirrors-pylint
      rev: 5e9df3b5d9e5c5819190217d0ef3f2dd2c521c33
      hooks:
          - id: pylint
            files: ^\W+/\W+.*.py$
            args: [--rcfile=./src/setup.cfg, --reports=no, --persistent=yes]
            stages: [manual]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: 85db7df3110ff1c3bad37caf79e0f465ba1570ee
      hooks:
          # - id: check-toml
          #   files: .toml$
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: [--fix=lf]
          - id: trailing-whitespace
          - id: check-merge-conflict
            stages: [merge-commit]
