---
version: '3.8'

services:
    black:
        extends:
            file: black/docker-compose.yaml
            service: black
    flake8:
        extends:
            file: flake8/docker-compose.yaml
            service: flake8
    hadolint:
        extends:
            file: hadolint/docker-compose.yaml
            service: hadolint
    mypy:
        extends:
            file: mypy/docker-compose.yaml
            service: mypy
    pre-commit:
        extends:
            file: pre-commit/docker-compose.yaml
            service: pre-commit
    pylint:
        extends:
            file: pylint/docker-compose.yaml
            service: pylint
    pytest:
        extends:
            file: pytest/docker-compose.yaml
            service: pytest
    python-dev:
        extends:
            file: python-dev/docker-compose.yaml
            service: python-dev
    sphinx:
        extends:
            file: sphinx/docker-compose.yaml
            service: sphinx
