sonar.projectKey=chrysa_usefull-containers
sonar.organization=chrysa
sonar.projectName=usefull-containers
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/node_modules/**,**/dist/**
sonar.coverage.exclusions=**
