sonar.projectKey=chrysa_satisfactory-factory-manager
sonar.organization=chrysa
sonar.projectName=satisfactory-factory-manager
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/__pycache__/**,**/*.pyc,**/docs/**,**/makefiles/**
