true:
  pull_request:
    paths:
    - .github/actionlint.yaml
    - .github/workflows/**
  push:
    branches:
    - develop
    - main
    - master
    paths:
    - .github/workflows/**
jobs:
  actionlint:
    name: Lint workflows
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false
    - name: Run actionlint
      uses: raven-actions/actionlint@3a24062651993d40fed1019b58ac6fbdfbf276cc
      with:
        matcher: true
name: Actionlint
permissions:
  contents: read
