---

services:
    pre-commit:
        build:
            context: .
            dockerfile: Dockerfile
            labels:
                maintainer: ${MAINTAINER_NAME-} <${MAINTAINER_MAIL}>
                build_date: ${BUILD_DATE:-}
                commit_id: ${CI_COMMIT_SHA:-}
                vcs-url: ${CI_REPOSITORY_URL:-}
                vcs-ref: ${CI_COMMIT_SHA:-}
                departement: QA
                description: guideline checker for python projects
                version: ${PRE_COMMIT_CONTAINER_VERSION}
        container_name: pre-commit
        environment:
            - GIT_DISCOVERY_ACROSS_FILESYSTEM=1
            - HOME=/tmp
            - PRE_COMMIT_HOME=/tmp/pre-commit-cache
            - PYTHONPYCACHEPREFIX=/tmp/pycache
            - RUFF_CACHE_DIR=/tmp/ruff-cache
            - MYPY_CACHE_DIR=/tmp/mypy-cache
        hostname: pre-commit
        image: ${DOCKER_REPO:-local}/pre-commit:${PRE_COMMIT_CONTAINER_VERSION}
        tty: true
        user: "${UID:-1000}:${GID:-1000}"
        volumes:
            - type: bind
              source: .
              target: /app
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock
        working_dir: /app
