services:
  bandit:
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        build_date: ${BUILD_DATE:-}
        commit_id: ${CI_COMMIT_SHA:-}
        departement: security
        description: Python security static analyser
        maintainer: ${MAINTAINER_NAME-} <${MAINTAINER_MAIL}>
        vcs-ref: ${CI_COMMIT_SHA:-}
        vcs-url: ${CI_REPOSITORY_URL:-}
        version: ${BANDIT_CONTAINER_VERSION}
    container_name: bandit
    image: ${DOCKER_REPO:-local}/bandit:${BANDIT_CONTAINER_VERSION}
    tty: true
    working_dir: /app
