services:
  mypy:
    build:
      cache_from:
      - ${DOCKER_REPO:-local}/mypy
      - python:3.8-alpine
      context: .
      dockerfile: Dockerfile
      labels:
        build_date: ${BUILD_DATE:-}
        commit_id: ${CI_COMMIT_SHA:-}
        departement: QA
        description: guideline checker for python projects
        maintainer: ${MAINTAINER_NAME-} <${MAINTAINER_MAIL}>
        vcs-ref: ${CI_COMMIT_SHA:-}
        vcs-url: ${CI_REPOSITORY_URL:-}
        version: ${MYPY_CONTAINER_VERSION}
    container_name: mypy
    image: ${DOCKER_REPO:-local}/mypy:${MYPY_CONTAINER_VERSION}
    tty: true
    working_dir: /app
