---
version: '3.9'

services:
    black:
        build:
            context: .
            dockerfile: Dockerfile
            labels:
                departement: QA
                description: linter for python projects
                version: ${BLACK_CONTAINER_VERSION}
                maintainer: ${MAINTAINER_NAME-} <${MAINTAINER_MAIL}>
                build_date: ${BUILD_DATE:-}
                commit_id: ${CI_COMMIT_SHA:-}
                vcs-url: ${CI_REPOSITORY_URL:-}
                vcs-ref: ${CI_COMMIT_SHA:-}
        command: --git
        container_name: black
        image: ${DOCKER_REPO:-local}/black:${BLACK_CONTAINER_VERSION}
        tty: true
        volumes:
            - .:/app
        working_dir: /app
