---

services:
    hadolint:
        build:
            context: .
            dockerfile: Dockerfile
            labels:
                maintainer: ${MAINTAINER_NAME-} <${MAINTAINER_MAIL}>
                build_date: ${BUILD_DATE:-}
                commit_id: ${CI_COMMIT_SHA:-}
                vcs-url: ${CI_REPOSITORY_URL:-}
                vcs-ref: ${CI_COMMIT_SHA:-}
                departement: QA
                description: guideline checker for python projects
                version: ${HADOLINT_CONTAINER_VERSION}
        container_name: hadolint
        image: ${DOCKER_REPO:-local}/hadolint:${HADOLINT_CONTAINER_VERSION}
        tty: true
        working_dir: /app
