---
version: '3.8'

services:
    python-dev:
        build:
            context: .
            dockerfile: Dockerfile
            labels:
                maintainer: ${MAINTAINER_NAME-} <${MAINTAINER_MAIL}>
                build_date: ${BUILD_DATE:-}
                commit_id: ${CI_COMMIT_SHA:-}
                vcs-url: ${CI_REPOSITORY_URL:-}
                vcs-ref: ${CI_COMMIT_SHA:-}
                departement: dev
                description: python container for dev
                version: ${PYTHON_DEV_CONTAINER_VERSION}
        container_name: python-dev
        image: ${DOCKER_REPO}/pylint:${PYTHON_DEV_CONTAINER_VERSION}
        tty: true
        volumes:
            - .:/app
        working_dir: /app
