services:
  ruff:
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        build_date: ${BUILD_DATE:-}
        commit_id: ${CI_COMMIT_SHA:-}
        departement: QA
        description: fast Python linter and formatter
        maintainer: ${MAINTAINER_NAME-} <${MAINTAINER_MAIL}>
        vcs-ref: ${CI_COMMIT_SHA:-}
        vcs-url: ${CI_REPOSITORY_URL:-}
        version: ${RUFF_CONTAINER_VERSION}
    container_name: ruff
    image: ${DOCKER_REPO:-local}/ruff:${RUFF_CONTAINER_VERSION}
    tty: true
    working_dir: /app
