services:
  reorder-python-imports:
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        build_date: ${BUILD_DATE:-}
        commit_id: ${CI_COMMIT_SHA:-}
        departement: QA
        description: linter for python projects
        maintainer: ${MAINTAINER_NAME-} <${MAINTAINER_MAIL}>
        vcs-ref: ${CI_COMMIT_SHA:-}
        vcs-url: ${CI_REPOSITORY_URL:-}
        version: ${reorder-python-imports_CONTAINER_VERSION}
    container_name: reorder-python-imports
    image: ${DOCKER_REPO:-local}/reorder-python-imports:${REORDER_PYTHON_IMPORTS_CONTAINER_VERSION}
    tty: true
    working_dir: /app
