services:
  flask-db-migrations:
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        build_date: ${BUILD_DATE:-}
        commit_id: ${CI_COMMIT_SHA:-}
        maintainer: ${MAINTAINER_NAME-} <${MAINTAINER_MAIL}>
        vcs-ref: ${CI_COMMIT_SHA:-}
        vcs-url: ${CI_REPOSITORY_URL:-}
    container_name: flask-db-migrations
    image: ${DOCKER_REPO:-local}/flask-db-migrations:${FLASK_DB_MIGRATIONS_CONTAINER_VERSION}
    tty: true
    working_dir: /app
