---
name: PR Dependency Check

on:
    pull_request_target:
        types: [closed, edited, opened, reopened]

permissions:
    issues: write
    pull-requests: write

jobs:
    check_dependencies:
        runs-on: ubuntu-latest
        name: Check PR dependencies

        steps:
            - name: Check dependencies
              uses: gregsdennis/dependencies-action@main
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Add dependent label
              if: >-
                  contains(github.event.pull_request.body, 'depends on') ||
                  contains(github.event.pull_request.body, 'blocked by')
              uses: actions/github-script@v9
              with:
                  script: |
                      await github.rest.issues.addLabels({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        issue_number: context.payload.pull_request.number,
                        labels: ['dependent'],
                      });
