"on":
  pull_request: null
  workflow_call: null
  workflow_dispatch: null
jobs:
  labels:
    name: Apply labels on pull request
    runs-on: ubuntu-latest
    steps:
    - name: Get Code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      with:
        persist-credentials: false
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: actions/labeler@b8dd2d9be0f68b860e7dae5dae7d772984eacd6d
      with:
        sync-labels: true
name: Pull Request Labels
permissions:
  contents: read
  pull-requests: write
run-name: "\U0001F3F7\uFE0F apply labeler by ${{ github.actor }}"
