"on":
  pull_request: null
  workflow_call: null
  workflow_dispatch: null
jobs:
  labels:
    name: Apply labels on pull request
    runs-on: ubuntu-latest
    steps:
    - name: Get Code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        persist-credentials: false
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213
      with:
        sync-labels: true
name: Pull Request Labels
permissions:
  contents: read
  pull-requests: write
run-name: "\U0001F3F7\uFE0F apply labeler by ${{ github.actor }}"
