"on":
  pull_request:
    branches-ignore:
    - develop
    - main
    - master
    types:
    - auto_merge_enabled
    - opened
    - ready_for_review
    - reopened
    - synchronize
  schedule:
  - cron: 0 0 * * *
  workflow_call: null
  workflow_dispatch: null
jobs:
  check_dependencies:
    name: Check Dependencies
    runs-on: ubuntu-latest
    steps:
    - env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: gregsdennis/dependencies-action@v1.4.2
    - uses: Levi-Lesches/blocking-issues@2eeffdc6b055341f635eb0f3e4aea671516a61dc
      with:
        use-label: Blocked
name: Check PR dependencies
permissions:
  contents: read
  pull-requests: write
run-name: ${{ github.workflow }} by ${{ github.actor }}
