---
name: Secret scan

on:
    push:
        branches: [main, develop, "feat/**", "feature/**", "fix/**", "release/**"]
    pull_request:
        branches: [main, develop, master]

permissions:
    contents: read
    pull-requests: read

jobs:
    call:
        uses: chrysa/github-actions/.github/workflows/secret-scan.yml@v1.2.0